spring:
  application:
    name: templatesbackend
  jpa:
  properties:
  hibernate.jdbc.batch_size: 25
  hibernate.order_inserts: true
  hibernate.order_updates: true
  hibernate.query.fail_on_pagination_over_collection_fetch: true
  hibernate.query.in_clause_parameter_padding: true
  hibernate:
  ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml


